/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mx.itson.autos.ui;

import com.sun.jdi.connect.spi.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import mx.itson.autos.entities.Clientes;
import mx.itson.autos.persistence.MySQLConnection;
import javax.swing.JPasswordField;
import mx.itson.autos.entities.CifradoUsuarios;
//import org.mindrot.jbcrypt.BCrypt;

/**
 *
 * @author angel
 */
public class FrameLogin extends javax.swing.JFrame {

    CifradoUsuarios cifrar = new CifradoUsuarios();

    //private javax.swing.JTextField usernameField;
    //private javax.swing.JPasswordField passwordField;
    /**
     * Creates new form FrameLogin
     */
    //MySQLConnection cx;
    public FrameLogin() {
        initComponents();
        //cx=new MySQLConnection.open

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnEntrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtContraseña = new javax.swing.JPasswordField();
        btnAdmi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnEntrar.setText("Entrar");
        BtnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        jLabel1.setText("Usuario");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 54, -1));

        jLabel2.setText("Contraseña");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));
        getContentPane().add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 130, 30));
        getContentPane().add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 164, 178, -1));

        btnAdmi.setText("Admins");
        btnAdmi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdmiActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdmi, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEntrarActionPerformed
        try {
            Clientes.ComprobarUsuario(txtUsuario.getText(), txtContraseña.getText());
            FrameCliente abrir = new FrameCliente();
            abrir.setVisible(true);
            this.setVisible(false);

//            JPasswordField txtContraseña = new JPasswordField();
//            txtContraseña.setEchoChar('*'); // Configurar el carácter de relleno
//            String usuario = txtUsuario.getText();
//            String contraseña = txtContraseña.getText();
//
//    // Consulta SQL para verificar las credenciales del administrador
//            String queryAdmin = "SELECT * FROM administrador WHERE usuario = ? AND contraseña = ?";
//
//    // Consulta SQL para verificar las credenciales del cliente
//            String queryCliente = "SELECT * FROM cliente WHERE nombre = ? AND contraseña = ?";
//
//            try ( java.sql.Connection conexion = MySQLConnection.get()) {
//                // Cifrar la contraseña antes de hacer la consulta SQL
//                String contraseñaCifrada = cifrar.cifrarCesar(contraseña, 3); // Utiliza tu método de cifrado
//
//                // Verificar si las credenciales corresponden a un administrador
//                try ( PreparedStatement statementAdmin = conexion.prepareStatement(queryAdmin)) {
//                    statementAdmin.setString(1, usuario);
//                    statementAdmin.setString(2, contraseñaCifrada); // Utiliza la contraseña cifrada
//                    try ( ResultSet resultSetAdmin = statementAdmin.executeQuery()) {
//                        if (resultSetAdmin.next()) {
//                            // Las credenciales son válidas para un administrador, abrir el JFrame MainAutos
//                            MainAutos mainAutos = new MainAutos();
//                            mainAutos.setVisible(true);
//                            dispose(); // Cerrar el JFrame actual
//                            return;
//                        }
//                    }
//                }
//
//                // Verificar si las credenciales corresponden a un cliente
//                try ( PreparedStatement statementCliente = conexion.prepareStatement(queryCliente)) {
//                    statementCliente.setString(1, usuario);
//                    statementCliente.setString(2, contraseñaCifrada); // Utiliza la contraseña cifrada
//                    try ( ResultSet resultSetCliente = statementCliente.executeQuery()) {
//                        if (resultSetCliente.next()) {
//                            // Las credenciales son válidas para un cliente, abrir el JFrame FrameAutos
//                            FrameAutos frameAutos = new FrameAutos();
//                            frameAutos.setVisible(true);
//                            dispose(); // Cerrar el JFrame actual
//                            return;
//                        }
//                    }
//                }
//
//                // Si no se encontró un usuario con las credenciales proporcionadas, mostrar un mensaje de error
//                JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos", "Error", JOptionPane.ERROR_MESSAGE);
//            } catch (SQLException ex) {
//                // Manejar cualquier error de SQL
//                ex.printStackTrace();
//            }
        } catch (SQLException ex) {
            Logger.getLogger(FrameLogin.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_BtnEntrarActionPerformed

    private void btnAdmiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdmiActionPerformed
        MainAutos abrir = new MainAutos();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAdmiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameLogin.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameLogin.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameLogin.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameLogin.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEntrar;
    private javax.swing.JButton btnAdmi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
